# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2561aef8e01392e2f05f2d841a739a4631b4628d7c31b1285fed531fd234af96555d1c7e7e979cddccb8f766ec444af8f676d31588a9f9c4539c60f07b005bd7

test:
  secret_key_base: bb469bd3bd95be5edc8527b13f96154d4be0c23ba0f586bcd45e103548841fd1e8b2dcc2e7301ccf13c911eb1782278fee5d4c374df55181946e3f396d94854f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
